### ISSUE TITLE
TODO v1

### ISSUE THREAD

**Issue by metiftikci** [ankareport/ankareport#1]
- [x] Better data source tree
  - [x] Set data source tree
- [x] Fix: Property grid can set different data source types
- [x] Fix: Move `Selector` keydown event from `document` to `element`
- [x] Section bindings
- [x] Delete item by delete key down
- [x] Sub sections
- [x] Add font and font-size variables
- [x] Remove section button on context menu
- [x] Implement `svg` icons
- [x] #2 
- [x] Line css for `Data Source`
- [x] Fix top-down style for report generation
- [x] Add onChange event
- [x] Fix elements. Adopt onChange event
- [x] Collapse Element(Section) by only arrow
- [x] Element click must select element
- [x] Add undo/redo #4
- [x] Fix report section default values
- [x] Multiple Selector
- [x] Number format
- [x] Date format
- [x] Add pdf and excel exporter #10
